[project]
name = "running-shoe-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.111",
  "uvicorn>=0.30",
  "pydantic>=2.8",
  "python-dotenv>=1.0",
  "httpx>=0.27",
  "requests>=2.31",
  "pytest>=8.2"
]

[tool.pytest.ini_options]
pythonpath = ["."]
